### ISSUE TITLE
Problem.

### ISSUE THREAD

**Issue by CrunchiChicken** [LostMyCode/javascript-deobfuscator#10]
The deobfuscating isn't working on this code 
https://pastebin.com/bwNC3syx

**Comment by LostMyCode** [comment]
I tried to fix the problem, but sadly, I couldn't :(
and I found a new problem.
I hope I can let you know that these problem fixed

**Comment by LostMyCode** [comment]
Now my deobfuscator can decode the one you sent `https://pastebin.com/bwNC3syx`.

![image](https://user-images.githubusercontent.com/63048878/91630676-3a7e0300-ea0e-11ea-878c-188a5d7c2353.png)
However, sadly, almost parts are not readable like this.
