### ISSUE TITLE
[HELP] TODO: Unicode Escape Sequence Support

### ISSUE THREAD

**Issue by LostMyCode** [LostMyCode/javascript-deobfuscator#11]
Hi. I am a dev of this repo. Can someone help my development?

My deobfuscator crashes if target code is generated with unicode escape sequence enabled. 
https://hastebin.com/raw/suyubepenu

I tried to fix the problem but... :(
I want to explain more details but its hard to me (im not an english)

**Comment by hotline1337** [comment]
Just copy the unicode sequence formatter from beautifier.io repo: https://github.com/beautifier/beautifier.io

**Comment by LostMyCode** [comment]
hmm ok i will try it

**Comment by LostMyCode** [comment]
I found a method to fix this issue
