### ISSUE TITLE
Error Invalid obfuscation type

### ISSUE THREAD

**Issue by bbday** [LostMyCode/javascript-deobfuscator#24]
https://obfuscator.io/
example code:
```
function hi() {
  console.log("Hello World!");
}
hi();
```

output:
`var _0x35e4=['1084824sdEayT','return\x20/\x22\x20','bind','504073uKzhvS','constructo','470775iPrxdC','nction()\x20','331777YYljVx','1007071aBnBUn','1lztQTk','return\x20(fu','rn\x20this\x22)(','prototype','apply','error','log','__proto__','Hello\x20Worl','491753KxDBmX','table','length','^([^\x20]+(\x20+','274557wkKsFU','test','info','trace','toString','warn','console'];var _0x1570=function(_0x5850ee,_0x331fe3){_0x5850ee=_0x5850ee-0x11f;var _0xe4d05e=_0x35e4[_0x5850ee];return _0xe4d05e;};(function(_0x628e9,_0x533dd3){var _0x372fb0=_0x1570;while(!![]){try{var _0x5c4dde=-parseInt(_0x372fb0(0x12a))+parseInt(_0x372fb0(0x123))+parseInt(_0x372fb0(0x139))+-parseInt(_0x372fb0(0x135))+-parseInt(_0x372fb0(0x128))+parseInt(_0x372fb0(0x126))*-parseInt(_0x372fb0(0x12c))+parseInt(_0x372fb0(0x12b));if(_0x5c4dde===_0x533dd3)break;else _0x628e9['push'](_0x628e9['shift']());}catch(_0x31662){_0x628e9['push'](_0x628e9['shift']());}}}(_0x35e4,0x8ab0a));function hi(){var _0x392672=_0x1570,_0x5d5a4d=function(){var _0x266744=!![];return function(_0x333bc7,_0x26c57a){var _0xdcfdca=_0x266744?function(){var _0x1d0265=_0x1570;if(_0x26c57a){var _0x55db0f=_0x26c57a[_0x1d0265(0x130)](_0x333bc7,arguments);return _0x26c57a=null,_0x55db0f;}}:function(){};return _0x266744=![],_0xdcfdca;};}(),_0x2734da=_0x5d5a4d(this,function(){var _0x53385b=function(){var _0x46b2bb=_0x1570,_0x1921e2=_0x53385b[_0x46b2bb(0x127)+'r'](_0x46b2bb(0x124)+'+\x20this\x20+\x20\x22'+'/')()[_0x46b2bb(0x127)+'r'](_0x46b2bb(0x138)+'[^\x20]+)+)+['+'^\x20]}');return!_0x1921e2[_0x46b2bb(0x13a)](_0x2734da);};return _0x53385b();});_0x2734da();var _0x4c9014=function(){var _0x29fca2=!![];return function(_0x519fa5,_0x5d069d){var _0x2a33ff=_0x29fca2?function(){if(_0x5d069d){var _0x59f962=_0x5d069d['apply'](_0x519fa5,arguments);return _0x5d069d=null,_0x59f962;}}:function(){};return _0x29fca2=![],_0x2a33ff;};}(),_0x4cfb50=_0x4c9014(this,function(){var _0x302407=_0x1570,_0xcc95e4;try{var _0x3274b5=Function(_0x302407(0x12d)+_0x302407(0x129)+('{}.constru'+'ctor(\x22retu'+_0x302407(0x12e)+'\x20)')+');');_0xcc95e4=_0x3274b5();}catch(_0x1ed911){_0xcc95e4=window;}var _0x30b9ab=_0xcc95e4['console']=_0xcc95e4[_0x302407(0x122)]||{},_0x42bc8c=[_0x302407(0x132),_0x302407(0x121),_0x302407(0x13b),_0x302407(0x131),'exception',_0x302407(0x136),_0x302407(0x11f)];for(var _0x1554f5=0x0;_0x1554f5<_0x42bc8c[_0x302407(0x137)];_0x1554f5++){var _0x1a208d=_0x4c9014['constructo'+'r'][_0x302407(0x12f)][_0x302407(0x125)](_0x4c9014),_0x4f723f=_0x42bc8c[_0x1554f5],_0x12eeb3=_0x30b9ab[_0x4f723f]||_0x1a208d;_0x1a208d[_0x302407(0x133)]=_0x4c9014[_0x302407(0x125)](_0x4c9014),_0x1a208d[_0x302407(0x120)]=_0x12eeb3['toString'][_0x302407(0x125)](_0x12eeb3),_0x30b9ab[_0x4f723f]=_0x1a208d;}});_0x4cfb50(),console['log'](_0x392672(0x134)+'d!');}hi();`

error:
[Error] Invalid obfuscation type! Please report to us or try again.

**Comment by LostMyCode** [comment]
https://github.com/LostMyCode/javascript-deobfuscator/issues/23
